// <auto-generated />
namespace Recuperos.Persistencia.BaseOracle.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class MigDicom : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MigDicom));
        
        string IMigrationMetadata.Id
        {
            get { return "202012181640074_MigDicom"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
