// <auto-generated />
namespace Recuperos.Persistencia.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class MigComplementoInfoPersona : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MigComplementoInfoPersona));
        
        string IMigrationMetadata.Id
        {
            get { return "202006210449480_MigComplementoInfoPersona"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
