// <auto-generated />
namespace Recuperos.Persistencia.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class MigCompaniaInt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MigCompaniaInt));
        
        string IMigrationMetadata.Id
        {
            get { return "202006192329129_MigCompaniaInt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
