CREATE GLOBAL TEMPORARY TABLE COLUMNAS_W (
  TNUMERO           NUMBER(10),
  TGASTOUF       NUMBER(18,2),
  TTIPOORDEN VARCHAR(15),
  TMONTOOR  NUMBER(10),
  TPROVISION NUMBER(18,2),
  TACEPTADA VARCHAR(2),
  TTIPODANIO VARCHAR(3)
);

drop table COLUMNAS_W;